name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pre-requisites
        run: |
          which envsubst
          which aws

      - name: Build website
        run: bash pugo.sh

      - name: Check HTML
        run: file template/resume.html