name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pre-requisites
        run: |
          which envsubst
          which aws

      - name: Build website
        run: bash pugo.sh

      - name: Check HTML
        run: file template/resume.html

      - name: S3 sync
        run: |
          aws s3 ls s3://${{ secrets.S3_BUCKET }}/ --human-readable --summarize
          aws s3 rm s3://${{ secrets.S3_BUCKET }} --recursive
          rm -f template/resume.html.template
          aws s3 sync template/ s3://${{ secrets.S3_BUCKET }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.CLOUDFRONT_ID }} --paths /
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: CloudFront status
        run: |
          sleep 5
          aws cloudfront list-distributions --query "DistributionList.Items[].{Status: Status, Domain: DomainName, OriginDomainName: Origins.Items[0].DomainName}[?contains(OriginDomainName, '${{ secrets.S3_BUCKET }}')] | [0]" | grep -q Deployed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}